import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/layout/sidebar/sidebar";
import Topbar from "@/components/layout/topbar/topbar";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const myFont = localFont({
  src: "../../public/fonts/NotoSansThai-VariableFont_wdth,wght.ttf",
  weight: "400",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="grid grid-rows-[60px_1fr] grid-cols-[250px_1fr] h-screen">
          <div className="col-span-2">
            <Topbar />
          </div>

          {/* Sidebar */}
          <div className="row-span-2">
            <Sidebar />
          </div>

          {/* Main Screen */}
          <div className={`bg-gray-200 p-6 col-start-2 row-start-2 h-full w-full overflow-auto ${myFont.className}`}>
            {children}
            {/* <main className="p-8 h-full w-full">{children}</main> */}
          </div>
        </div>
        {/* {children} */}
      </body>
    </html>
  );
}
