
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth/next"
import { authOptions } from "@/lib/authOptions";
import ClientLayout from "./client-layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions)


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-noto-sans-thai antialiased`}
      >
        <ClientLayout session={session}>{children}</ClientLayout>


      </body>
    </html>
  );
}
